config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :dogs, only: [:index, :show, :create, :new, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/dashboard", to: "pages#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user
end

app/models/dog.rb
class Dog < ApplicationRecord
  geocoded_by :address
  belongs_to :user
  has_one_attached :photo
  after_validation :geocode
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @dog = Dog.find(params[:dog_id])
  end

  def create
    @user = current_user
    @booking = Booking.new(booking_params)
    @dog = Dog.find(params[:dog_id])
    @booking.dog = @dog
    @booking.user = @user
    if @booking.save
      redirect_to dashboard_path, notice: "Yay you made a booking!"
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:beginning, :end, :user)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index  ]

  def index
    @dogs = Dog.all

      @markers = @dogs.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        info_window: render_to_string(partial: "info_window", locals: { dog: dog }),
        # image_url: helpers.asset_url("http://res.cloudinary.com/psmkr/image/upload/c_fill/v1/development/#{dog.photo.key}")
      }
  end
end

  def show
     @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @user = current_user
    @dog = Dog.new(dog_params)
    @dog.user = @user
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new
    end

  end

  def destroy
    @dog = set_dog
    @dog.delete
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:price, :name, :gender, :breed, :age, :size, :description, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end


  def dashboard
    @user = current_user
    @bookings = Booking.where(user_id:@user)

    @dogs = Dog.where(user_id:@user)

    # raise
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for [@dog, @booking] do |f| %>
  <%= f.input :beginning %>
  <%= f.input :end %>

  <%= f.submit %>
<% end %>

<%= link_to "Back", dog_path(@dog) %>

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :name %>
  <%= f.input :gender %>
  <%= f.input :breed %>
  <%= f.input :size %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

<%# <%= f.error_notification %>
  <%# <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.address %></p>

app/views/dogs/index.html.erb
<h1 class="p-2">This is all Dogs</h1>

<div class="d-flex">
  <div class="cards">
    <% @dogs.each do |dog| %>
      <div class="row m-2">
        <div class="card-product">
          <% if dog.photo.attached? %>
            <%=cl_image_tag dog.photo.key, crop: :fill %>
          <% end %>
          <div class="card-product-infos">
            <h2><%= link_to dog.name, dog_path(dog), style:"text-decoration:none; color:black" %></h2>
            <p><%= link_to dog.breed, dog_path(dog), style:"text-decoration:none; color:black" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div id="map">
  <div style="width: 600px; height: 700px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="d-flex p-2 ">
<div class="p-2">
<h2>Tell us about your dog!</h2>
</div>
<div class="p-2">
<%= render "form", dog: @dog %>
</div>

</div>
<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<div class="container">

<h1>Look at this dog!</h1>
<div class="d-inline-flex p-2">
<div>
<%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>
<hr>
<%= link_to "Book this dawg!",  new_dog_booking_path(@dog) %>
<hr>
<%=link_to "Go back to all the dogs.", dogs_path %>

</div>

<%# <h2>And all the information about it:</h2> %>
<div>

<ul>
  <h2><%= @dog.name %></h2>
  <br>
  <p>Age: <%= @dog.age %></p>
  <br>
  <p>Breed: <%= @dog.breed %></p>
  <br>
  <p>Size: <%= @dog.size %></p>
  <br>
  <p>Gender: <%= @dog.gender %></p>
  <br>
  <%=
  "#{@dog.name} is a cuddly and feisty little teddy bear, who likes to be petted, often putting their front paws on your knee asking for attention. #{@dog.name} braves the other dogs to vie for lap-time - then they lays sideways on your chest and snuggles their head under your chin. #{@dog.name}'s hair is very soft. #{@dog.name} can be playful with their human but not that interactive with the other dogs. When breakfast and dinner is getting dished up, #{@dog.name} barks and barks - the best times of the day. #{@dog.name} does sit before getting their food dish if asked. #{@dog.name} likes to be an only pet; they chase the cats and learned other dogs have boundaries and don’t share their food bowls. #{@dog.name} has gotten much more social with other people but not fond of young children. After they get petted, they go to the couch, kick back and keeps a curious eye on what’s going on. #{@dog.name} is a really cute and fun little dog. They can be quite social or the best nap-buddy you’ve ever had."
   %>
</ul>


</div>
</div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RbnbDoggo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="container">
    <%= yield %>
    </div>


  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
<h1>Dashboard</h1>

 <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
<%= link_to "Add your Picture",  edit_user_registration_path %>

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Your Bookings</h2>
      <% @bookings.each do |booking| %>

      <p><%= "You booked #{booking.dog.name}" %></p>

      <% end %>


      <%=link_to "Rent your Dog", new_dog_path, class:"btn btn-primary" %>
    </div>
    <div class="col">
      <h2>Your dogs</h2>

      <% @dogs.each do |dog| %>

      <p><%= "#{dog.name}" %></p>

      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <header class="header">
    <div class = "logo"></div>
    <h2 class ="lang"></h2>
    <h2 class = "currency"></h2>
    <h2 class = "become"> </h2>
    <h2 class = "help"></h2>
    <h2 class = "reg"></h2>
    <h2 class = "log">Login</h2>
  </header>
  <div class = "center-searchbar">
  <%= link_to "discover them dogs", dogs_path, class: "btn btn-success"%>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "noun-dog-1035865.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dogs", dogs_path , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.key %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add dog", new_dog_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>